print("-" * 21)
print("Tabla de verdad")
print("-" * 21)
print("{:5} | {:5} | {:5}".format("A", "B", "A | B"))
print("{:5} | {:5} | {:5}".format(True, True, True or True))
print("{:5} | {:5} | {:5}".format(True, False, True or False))
print("{:5} | {:5} | {:5}".format(False, True, False or True))
print("{:5} | {:5} | {:5}".format(True, False, True or False))
print("{:5} | {:5} | {:5}".format(False, False, False or False))
print("-" * 21)